### ISSUE TITLE
Cannot find headers

### ISSUE THREAD

**Issue by AryzenRS** [henrybetts/swift-webgpu#9]
Hello!

I am attempting to use this package as per the directions, however, I get the error `webgpu/webgpu.h file not found`; I have attempted to add the include directory both via `cSettings.headerSearchPath` as well as `publicHeadersPath` in my Package.swift but neither allow it to recognize the header. I'm not sure what I'm doing wrong (or if it's appropriate to have put this in an issue since I don't think I've ever written an issue before)

**Comment by henrybetts** [comment]
I'm guessing this is because headerSearchPath doesn't allow you to specify an absolute path, and it also doesn't propagate to dependencies.

I've made some changes today, and my recommendation now is to install Dawn system-wide (i.e. to /usr/local). This should allow Swift to find it automatically, hopefully making the whole process a bit easier, at least until Dawn has some kind of official build/pkg-config.

**Comment by AryzenRS** [comment]
The new build instructions are significantly easier. For future reference perhaps also mention which Windows directories to use (if it would work with Win). I have a separate build problem now but I'll make a new issue for it.
